name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

    # 🟢 React Frontend
    - name: Install frontend dependencies
      run: |
        cd 01-Frontend
        npm install
        npm run build

    # 🔵 Node Backend
    - name: Install backend dependencies
      run: |
        cd 02-Server
        npm install

    # 🟣 FastAPI (Python)
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        cd 03-backend-ai
        pip install -r requirements.txt